import "vuetify/styles";
import "@mdi/font/css/materialdesignicons.css";
import { createVuetify } from "vuetify";
import {
  VApp,
  VLayout,
  VContainer,
  VAppBar,
  VMain,
  VFooter,
  VRow,
  VCol,
  VCard,
  VToolbar,
  VToolbarTitle,
  VCardTitle,
  VCardText,
  VCardItem,
  VCardActions,
  VTextField,
  VPagination,
  VProgressLinear,
  VChip,
  VChipGroup,
  VBtn,
  VBtnGroup,
  VIcon,
  VSpacer,
  VDivider,
  VDialog,
  VList,
  VSelect,
  VTable,
  VProgressCircular,
  VOverlay,
} from "vuetify/components";
import { Intersect } from "vuetify/directives";

export default createVuetify({
  theme: {
    defaultTheme: "dark",
  },
  directives: {
    Intersect,
  },
  components: {
    VApp,
    VLayout,
    VContainer,
    VAppBar,
    VMain,
    VFooter,
    VRow,
    VCol,
    VCard,
    VToolbar,
    VToolbarTitle,
    VCardTitle,
    VCardText,
    VCardItem,
    VCardActions,
    VTextField,
    VPagination,
    VProgressLinear,
    VChip,
    VChipGroup,
    VBtn,
    VBtnGroup,
    VIcon,
    VSpacer,
    VDivider,
    VDialog,
    VList,
    VSelect,
    VTable,
    VProgressCircular,
    VOverlay,
  },
  defaults: {},
});
